# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.srcs/sources_1/bd/mac_udp_design/ip/mac_udp_design_fifo_generator_0_2/mac_udp_design_fifo_generator_0_2.xci
# IP: The module: 'mac_udp_design_fifo_generator_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_fifo_generator_0_2/mac_udp_design_fifo_generator_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_udp_design_fifo_generator_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_fifo_generator_0_2/mac_udp_design_fifo_generator_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_udp_design_fifo_generator_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.srcs/sources_1/bd/mac_udp_design/ip/mac_udp_design_fifo_generator_0_2/mac_udp_design_fifo_generator_0_2.xci
# IP: The module: 'mac_udp_design_fifo_generator_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_fifo_generator_0_2/mac_udp_design_fifo_generator_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_udp_design_fifo_generator_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_fifo_generator_0_2/mac_udp_design_fifo_generator_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_udp_design_fifo_generator_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
