# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.runs/synth_1/mac_udp_design_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 6
set_param bd.open.in_stealth_mode 3
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.cache/wt [current_project]
set_property parent.project_path C:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/ip_repo/mac_filter_1_0 [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/hdl/mac_udp_design_wrapper.v
add_files C:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.srcs/sources_1/bd/mac_udp_design/mac_udp_design.bd
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_dma_0_1/mac_udp_design_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_dma_0_1/mac_udp_design_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_dma_0_1/mac_udp_design_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_dma_PS2PL_0/mac_udp_design_axi_dma_PS2PL_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_dma_PS2PL_0/mac_udp_design_axi_dma_PS2PL_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_dma_PS2PL_0/mac_udp_design_axi_dma_PS2PL_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_1/bd_0/ip/ip_1/bd_1adb_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_1/bd_0/ip/ip_1/bd_1adb_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_1/bd_0/ip/ip_5/bd_1adb_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_1/bd_0/ip/ip_6/bd_1adb_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_1/bd_0/ip/ip_7/bd_1adb_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_1/bd_0/ip/ip_8/bd_1adb_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_1/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_1/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_1/bd_1b9b_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_1/bd_1b9b_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_5/bd_1b9b_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_6/bd_1b9b_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_7/bd_1b9b_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_8/bd_1b9b_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_9/bd_1b9b_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_processing_system7_0_5/mac_udp_design_processing_system7_0_5.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_1/bd_7027_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_1/bd_7027_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_2/bd_7027_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_3/bd_7027_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_4/bd_7027_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_5/bd_7027_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_6/bd_7027_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_7/bd_7027_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_8/bd_7027_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_9/bd_7027_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_10/bd_7027_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_11/bd_7027_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_12/bd_7027_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_13/bd_7027_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_14/bd_7027_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_15/bd_7027_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_16/bd_7027_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_20/bd_7027_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_21/bd_7027_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_22/bd_7027_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_23/bd_7027_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_24/bd_7027_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_25/bd_7027_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_26/bd_7027_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_27/bd_7027_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_28/bd_7027_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_29/bd_7027_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_30/bd_7027_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_31/bd_7027_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_33/bd_7027_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_34/bd_7027_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_35/bd_7027_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_36/bd_7027_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_37/bd_7027_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/bd_0/ip/ip_38/bd_7027_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_axi_smc_4/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_rst_ps7_0_50M_1/mac_udp_design_rst_ps7_0_50M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_rst_ps7_0_50M_1/mac_udp_design_rst_ps7_0_50M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_rst_ps7_0_50M_1/mac_udp_design_rst_ps7_0_50M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/mac_udp_design_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.srcs/utils_1/imports/synth_1/mac_udp_design_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mac_udp_design_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mac_udp_design_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file mac_udp_design_wrapper_utilization_synth.rpt -pb mac_udp_design_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
