# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.srcs/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/mac_udp_design_smartconnect_0_2.xci
# IP: The module: 'mac_udp_design_smartconnect_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/bd_1b9b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_0/bd_1b9b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_1/bd_1b9b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_2/bd_1b9b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_3/bd_1b9b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_4/bd_1b9b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_5/bd_1b9b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_6/bd_1b9b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_7/bd_1b9b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_8/bd_1b9b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_9/bd_1b9b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_10/bd_1b9b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_1/bd_1b9b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_1/bd_1b9b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_5/bd_1b9b_s00a2s_0_ooc.xdc

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_6/bd_1b9b_sawn_0_ooc.xdc

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_7/bd_1b9b_swn_0_ooc.xdc

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_8/bd_1b9b_sbn_0_ooc.xdc

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_9/bd_1b9b_m00s2a_0_ooc.xdc

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_udp_design_smartconnect_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_udp_design_smartconnect_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.srcs/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/mac_udp_design_smartconnect_0_2.xci
# IP: The module: 'mac_udp_design_smartconnect_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/bd_1b9b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_0/bd_1b9b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_1/bd_1b9b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_2/bd_1b9b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_3/bd_1b9b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_4/bd_1b9b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_5/bd_1b9b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_6/bd_1b9b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_7/bd_1b9b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_8/bd_1b9b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_9/bd_1b9b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_10/bd_1b9b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_1/bd_1b9b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_1/bd_1b9b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_5/bd_1b9b_s00a2s_0_ooc.xdc

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_6/bd_1b9b_sawn_0_ooc.xdc

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_7/bd_1b9b_swn_0_ooc.xdc

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_8/bd_1b9b_sbn_0_ooc.xdc

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/bd_0/ip/ip_9/bd_1b9b_m00s2a_0_ooc.xdc

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_udp_design_smartconnect_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/gsfei/OneDrive/Desktop/networkaccel_project/vivado/vivado.gen/sources_1/bd/mac_udp_design/ip/mac_udp_design_smartconnect_0_2/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_udp_design_smartconnect_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
